### ISSUE TITLE
Front page images

### ISSUE THREAD

**Issue by ryanerickson** [peacefulrespite/dracky#1]
Though I know this isn't the correct place I couldn't find where to comment... at any rate, how did you get the photos to show up on the front page? I've been looking for about three weeks on how to do so with no luck.

~ryan

**Comment by brettchalupa** [comment]
@ryanerickson here's the commit that shows the changes to the theme to render the images on the front-page: https://github.com/peacefulrespite/dracky/commit/6366992cee90a636da5abbc0c390c2a727b162ee

I created this theme for my tweaks to the default Casper theme. Let me know if you have any questions. I'm going to close this issue out.
